### ISSUE TITLE
Documentation and Demo request

### ISSUE THREAD

**Issue by theefreelancer** [Oblosys/react-hook-tracer#1]
Thanks for the good work with the react-hook-tracer project, i really applaud you for that.
I believe your projects specifically this one needs more traction, purposefully because of its ability to help programmers and developers understand how different components work in the hood.
That's why i am requesting for a demo probably a worked out video for many people out there who would love to use this package.

**Comment by Oblosys** [comment]
Thanks, glad you like the package! The general interest in it is a bit underwhelming though, which make it tricky for me to justify spending much more time on it. A demo video would be great, but since the repo only gets 1 or 2 page views a day, I frankly don't think it's worth the effort as no one will see it.

I might be able to add a few bits of documentation over time though. Is there something specific you feel that's missing or unclear in the current example? There are a few more small examples in [`/apps/react-hook-tracer-demo/src/demos/`](https://github.com/Oblosys/react-hook-tracer/tree/main/apps/react-hook-tracer-demo/src/demos), which are also live on the CodeSandbox playground, but maybe that's not made clear enough on the landing page.

**Comment by Oblosys** [comment]
I'll close the issue for now. Feel free to reopen it if you have any specific documentation requests.
